import { Question } from "./types";

export const seedQuestions: Question[] = [
  // PHARMA — General Pharmacology (5)
  {
    id: "ph1", text: "Which cytochrome P450 enzyme is responsible for the metabolism of approximately 25% of all clinically used drugs?",
    options: ["CYP1A2", "CYP2D6", "CYP3A4", "CYP2C19"], correctAnswer: 2,
    explanation: "CYP3A4 is the most abundant CYP enzyme in the liver and small intestine, metabolizing approximately 50% of drugs. CYP2D6 handles about 25%.",
    exam: "DHA", specialty: "pharmacy", topic: "PHARMA", difficulty: 1, phase: 1, day: 1,
  },
  {
    id: "ph2", text: "A competitive antagonist shifts the dose-response curve of an agonist:",
    options: ["To the left without changing Emax", "To the right without changing Emax", "Downward, reducing Emax", "Does not affect the curve"],
    correctAnswer: 1,
    explanation: "A competitive antagonist increases the EC50 (shifts curve right) but does not change the maximum efficacy (Emax) since it can be overcome by increasing agonist concentration.",
    exam: "MOH", specialty: "pharmacy", topic: "PHARMA", difficulty: 1, phase: 1, day: 1,
  },
  {
    id: "ph3", text: "Which drug has the highest therapeutic index?",
    options: ["Digoxin", "Warfarin", "Penicillin", "Lithium"],
    correctAnswer: 2,
    explanation: "Penicillin has a very wide therapeutic index (high safety margin). Digoxin, warfarin, and lithium all have narrow therapeutic indices requiring monitoring.",
    exam: "SLE", specialty: "pharmacy", topic: "PHARMA", difficulty: 1, phase: 1, day: 2,
  },
  {
    id: "ph4", text: "Which receptor type is directly linked to an ion channel?",
    options: ["G-protein coupled receptor", "Nicotinic acetylcholine receptor", "Insulin receptor", "Intracellular steroid receptor"],
    correctAnswer: 1,
    explanation: "Nicotinic receptors are ligand-gated ion channels (ionotropic). Binding of ACh opens the Na+ channel directly, producing rapid responses in milliseconds.",
    exam: "HAAD", specialty: "pharmacy", topic: "PHARMA", difficulty: 2, phase: 1, day: 2,
  },
  {
    id: "ph5", text: "Tachyphylaxis is best described as:",
    options: ["Gradual decrease in response over weeks", "Rapid decrease in response after repeated doses", "Increased sensitivity to a drug", "Allergic reaction to a drug"],
    correctAnswer: 1,
    explanation: "Tachyphylaxis is a rapid decrease in drug response after repeated administration over a short period, distinct from tolerance which develops more gradually.",
    exam: "DHA", specialty: "pharmacy", topic: "PHARMA", difficulty: 1, phase: 1, day: 1,
  },

  // CVS — Cardiovascular (5)
  {
    id: "cv1", text: "Which antihypertensive is the drug of choice in a pregnant woman with chronic hypertension?",
    options: ["Lisinopril", "Methyldopa", "Losartan", "Hydrochlorothiazide"],
    correctAnswer: 1,
    explanation: "Methyldopa is the preferred antihypertensive in pregnancy due to its long safety record. ACE inhibitors and ARBs are teratogenic and contraindicated.",
    exam: "DHA", specialty: "pharmacy", topic: "CVS", difficulty: 1, phase: 1, day: 9,
  },
  {
    id: "cv2", text: "A patient on warfarin starts taking amiodarone. What is the expected effect?",
    options: ["Decreased INR", "No change in INR", "Increased INR", "Warfarin becomes ineffective"],
    correctAnswer: 2,
    explanation: "Amiodarone inhibits CYP2C9 and CYP3A4, which metabolize warfarin. This increases warfarin levels and INR, raising bleeding risk. Warfarin dose should be reduced by 30-50%.",
    exam: "MOH", specialty: "pharmacy", topic: "CVS", difficulty: 2, phase: 2, day: 13,
  },
  {
    id: "cv3", text: "Which beta-blocker has intrinsic sympathomimetic activity (ISA)?",
    options: ["Metoprolol", "Atenolol", "Pindolol", "Propranolol"],
    correctAnswer: 2,
    explanation: "Pindolol has intrinsic sympathomimetic activity, meaning it partially activates beta receptors while blocking the effect of catecholamines. This results in less resting bradycardia.",
    exam: "SLE", specialty: "pharmacy", topic: "CVS", difficulty: 2, phase: 2, day: 9,
  },
  {
    id: "cv4", text: "The mechanism of action of clopidogrel is:",
    options: ["COX-1 inhibition", "Irreversible P2Y12 ADP receptor blockade", "GPIIb/IIIa receptor antagonism", "Phosphodiesterase inhibition"],
    correctAnswer: 1,
    explanation: "Clopidogrel is a prodrug that irreversibly blocks the P2Y12 ADP receptor on platelets, inhibiting ADP-mediated platelet activation and aggregation for the platelet's lifetime.",
    exam: "HAAD", specialty: "pharmacy", topic: "CVS", difficulty: 2, phase: 1, day: 14,
  },
  {
    id: "cv5", text: "Which statin has the lowest risk of drug interactions due to minimal CYP450 metabolism?",
    options: ["Simvastatin", "Atorvastatin", "Rosuvastatin", "Lovastatin"],
    correctAnswer: 2,
    explanation: "Rosuvastatin undergoes minimal CYP450 metabolism (only ~10% via CYP2C9), making it less prone to drug interactions compared to simvastatin and atorvastatin (CYP3A4).",
    exam: "DHA", specialty: "pharmacy", topic: "CVS", difficulty: 2, phase: 2, day: 12,
  },

  // CNS — Central Nervous System (5)
  {
    id: "cn1", text: "Which SSRI has the longest half-life and active metabolite?",
    options: ["Sertraline", "Paroxetine", "Fluoxetine", "Escitalopram"],
    correctAnswer: 2,
    explanation: "Fluoxetine has a half-life of 1-3 days, and its active metabolite norfluoxetine has a half-life of 4-16 days. This long duration allows for easier tapering and less withdrawal risk.",
    exam: "DHA", specialty: "pharmacy", topic: "CNS", difficulty: 1, phase: 1, day: 29,
  },
  {
    id: "cn2", text: "Serotonin syndrome is most likely when combining an SSRI with:",
    options: ["Acetaminophen", "Linezolid", "Amoxicillin", "Omeprazole"],
    correctAnswer: 1,
    explanation: "Linezolid is a reversible MAO inhibitor. Combining it with SSRIs can cause serotonin syndrome — characterized by hyperthermia, clonus, agitation, and potentially death.",
    exam: "MOH", specialty: "pharmacy", topic: "CNS", difficulty: 2, phase: 2, day: 29,
  },
  {
    id: "cn3", text: "Which benzodiazepine does NOT undergo hepatic oxidation and is preferred in liver disease?",
    options: ["Diazepam", "Lorazepam", "Midazolam", "Chlordiazepoxide"],
    correctAnswer: 1,
    explanation: "Lorazepam (along with oxazepam and temazepam — 'LOT') undergoes only glucuronidation, not oxidative metabolism, making them safer in hepatic impairment.",
    exam: "SLE", specialty: "pharmacy", topic: "CNS", difficulty: 2, phase: 2, day: 29,
  },
  {
    id: "cn4", text: "Which antiepileptic drug is most associated with Stevens-Johnson syndrome in HLA-B*1502 carriers?",
    options: ["Valproic acid", "Levetiracetam", "Carbamazepine", "Gabapentin"],
    correctAnswer: 2,
    explanation: "Carbamazepine has a strong association with SJS/TEN in patients carrying HLA-B*1502 (common in Southeast Asian populations). FDA recommends genetic testing before prescribing.",
    exam: "HAAD", specialty: "pharmacy", topic: "CNS", difficulty: 3, phase: 3, day: 34,
  },
  {
    id: "cn5", text: "The mechanism of action of levodopa in Parkinson's disease is:",
    options: ["Direct dopamine receptor agonism", "MAO-B inhibition", "Conversion to dopamine in the CNS", "COMT inhibition"],
    correctAnswer: 2,
    explanation: "Levodopa is the metabolic precursor to dopamine. It crosses the BBB and is converted to dopamine by DOPA decarboxylase in the brain, replenishing depleted dopamine stores.",
    exam: "DHA", specialty: "pharmacy", topic: "CNS", difficulty: 1, phase: 1, day: 33,
  },

  // ENDO — Endocrinology (5)
  {
    id: "en1", text: "Which diabetes medication carries the highest risk of hypoglycemia when used as monotherapy?",
    options: ["Metformin", "Glipizide", "Sitagliptin", "Empagliflozin"],
    correctAnswer: 1,
    explanation: "Sulfonylureas like glipizide stimulate insulin secretion regardless of blood glucose levels, making hypoglycemia their most common and dangerous adverse effect.",
    exam: "DHA", specialty: "pharmacy", topic: "ENDO", difficulty: 1, phase: 1, day: 27,
  },
  {
    id: "en2", text: "Metformin is contraindicated when eGFR falls below:",
    options: ["60 mL/min", "45 mL/min", "30 mL/min", "15 mL/min"],
    correctAnswer: 2,
    explanation: "Metformin is contraindicated when eGFR < 30 mL/min due to increased risk of lactic acidosis. It should be used with caution at eGFR 30-45 mL/min with dose reduction.",
    exam: "MOH", specialty: "pharmacy", topic: "ENDO", difficulty: 2, phase: 2, day: 27,
  },
  {
    id: "en3", text: "Which insulin analog has the longest duration of action?",
    options: ["Insulin lispro", "Insulin glargine U-100", "Insulin degludec", "NPH insulin"],
    correctAnswer: 2,
    explanation: "Insulin degludec (Tresiba) has a duration of action exceeding 42 hours with a half-life of ~25 hours, the longest of any insulin. Glargine U-100 lasts ~24 hours.",
    exam: "SLE", specialty: "pharmacy", topic: "ENDO", difficulty: 2, phase: 2, day: 27,
  },
  {
    id: "en4", text: "Levothyroxine should be taken:",
    options: ["With food to enhance absorption", "30-60 minutes before breakfast on an empty stomach", "At bedtime with a snack", "With calcium supplements"],
    correctAnswer: 1,
    explanation: "Levothyroxine should be taken on an empty stomach 30-60 minutes before eating. Food, calcium, iron, and antacids significantly reduce its absorption.",
    exam: "HAAD", specialty: "pharmacy", topic: "ENDO", difficulty: 1, phase: 1, day: 24,
  },
  {
    id: "en5", text: "SGLT2 inhibitors (e.g., empagliflozin) reduce cardiovascular risk primarily by:",
    options: ["Lowering HbA1c", "Reducing blood pressure and fluid volume", "Increasing insulin sensitivity", "Inhibiting glucagon secretion"],
    correctAnswer: 1,
    explanation: "SGLT2 inhibitors' cardiovascular benefits are thought to be largely independent of glucose lowering, primarily mediated through osmotic diuresis, natriuresis, and reduced preload/afterload.",
    exam: "DHA", specialty: "pharmacy", topic: "ENDO", difficulty: 3, phase: 3, day: 27,
  },

  // INFEC — Infectious Disease (5)
  {
    id: "in1", text: "Which antibiotic requires renal dose adjustment AND therapeutic drug monitoring?",
    options: ["Amoxicillin", "Vancomycin", "Azithromycin", "Doxycycline"],
    correctAnswer: 1,
    explanation: "Vancomycin is renally cleared and nephrotoxic. Trough levels (or AUC/MIC) must be monitored to ensure efficacy (target AUC/MIC 400-600) while minimizing nephrotoxicity.",
    exam: "DHA", specialty: "pharmacy", topic: "INFEC", difficulty: 1, phase: 1, day: 36,
  },
  {
    id: "in2", text: "The mechanism of resistance of MRSA to beta-lactams is:",
    options: ["Beta-lactamase production", "Altered PBP2a (mecA gene)", "Efflux pump", "Porin mutation"],
    correctAnswer: 1,
    explanation: "MRSA resistance is due to the mecA gene encoding PBP2a, an altered penicillin-binding protein with low affinity for beta-lactams. This is distinct from beta-lactamase production.",
    exam: "MOH", specialty: "pharmacy", topic: "INFEC", difficulty: 2, phase: 2, day: 36,
  },
  {
    id: "in3", text: "Which antifungal inhibits ergosterol synthesis by blocking 14-alpha-demethylase?",
    options: ["Amphotericin B", "Fluconazole", "Caspofungin", "Nystatin"],
    correctAnswer: 1,
    explanation: "Azole antifungals (fluconazole, itraconazole, voriconazole) inhibit CYP450 14-alpha-demethylase (lanosterol demethylase), blocking ergosterol synthesis in fungal cell membranes.",
    exam: "SLE", specialty: "pharmacy", topic: "INFEC", difficulty: 1, phase: 1, day: 40,
  },
  {
    id: "in4", text: "Which antibiotic is MOST associated with QT prolongation?",
    options: ["Amoxicillin", "Ciprofloxacin", "Azithromycin", "Doxycycline"],
    correctAnswer: 2,
    explanation: "Azithromycin carries an FDA warning for QT prolongation and risk of torsades de pointes. While fluoroquinolones also prolong QT, azithromycin has a more prominent warning.",
    exam: "HAAD", specialty: "pharmacy", topic: "INFEC", difficulty: 2, phase: 2, day: 39,
  },
  {
    id: "in5", text: "The drug of choice for Clostridioides difficile initial non-severe infection is:",
    options: ["Metronidazole IV", "Oral vancomycin", "Fidaxomicin", "Oral metronidazole"],
    correctAnswer: 2,
    explanation: "Per IDSA 2021 guidelines, fidaxomicin is preferred for initial C. diff episodes. Oral vancomycin is also acceptable. Metronidazole is now only recommended if vancomycin/fidaxomicin are unavailable.",
    exam: "DHA", specialty: "pharmacy", topic: "INFEC", difficulty: 3, phase: 3, day: 36,
  },

  // KIN — Pharmacokinetics (5)
  {
    id: "ki1", text: "A drug with first-order elimination kinetics has a half-life of 6 hours. How long to reach steady state?",
    options: ["6 hours", "12 hours", "24 hours", "30 hours"],
    correctAnswer: 3,
    explanation: "Steady state is reached in approximately 4-5 half-lives. 5 × 6 hours = 30 hours. At this point, the rate of drug input equals the rate of elimination.",
    exam: "DHA", specialty: "pharmacy", topic: "KIN", difficulty: 1, phase: 1, day: 19,
  },
  {
    id: "ki2", text: "Bioavailability of an IV drug is always:",
    options: ["Variable", "50%", "100%", "Depends on the drug"],
    correctAnswer: 2,
    explanation: "IV administration bypasses all absorption barriers, delivering 100% of the drug directly to the systemic circulation. By definition, IV bioavailability (F) = 1 or 100%.",
    exam: "MOH", specialty: "pharmacy", topic: "KIN", difficulty: 1, phase: 1, day: 19,
  },
  {
    id: "ki3", text: "Which factor most significantly increases the volume of distribution of a lipophilic drug?",
    options: ["High plasma protein binding", "Low tissue binding", "High lipid solubility", "Renal impairment"],
    correctAnswer: 2,
    explanation: "High lipid solubility allows extensive distribution into tissues (especially fat), greatly increasing Vd. A large Vd indicates the drug distributes widely outside the plasma compartment.",
    exam: "SLE", specialty: "pharmacy", topic: "KIN", difficulty: 2, phase: 2, day: 20,
  },
  {
    id: "ki4", text: "Zero-order kinetics means:",
    options: ["Rate of elimination is proportional to drug concentration", "A constant amount of drug is eliminated per unit time", "The drug is eliminated in zero hours", "The drug has no elimination"],
    correctAnswer: 1,
    explanation: "Zero-order kinetics: a constant AMOUNT of drug is eliminated per unit time regardless of concentration (e.g., ethanol, phenytoin at high levels, aspirin overdose).",
    exam: "HAAD", specialty: "pharmacy", topic: "KIN", difficulty: 1, phase: 1, day: 19,
  },
  {
    id: "ki5", text: "Clearance is best defined as:",
    options: ["Volume of drug eliminated per unit time", "Volume of plasma completely cleared of drug per unit time", "Amount of drug excreted in urine", "Half-life divided by Vd"],
    correctAnswer: 1,
    explanation: "Clearance (CL) is the volume of plasma from which drug is completely removed per unit time (mL/min or L/hr). CL = Rate of elimination / Plasma concentration.",
    exam: "DHA", specialty: "pharmacy", topic: "KIN", difficulty: 2, phase: 2, day: 20,
  },

  // CAL — Pharmaceutical Calculations (5)
  {
    id: "ca1", text: "How many milligrams of NaCl are needed to prepare 500 mL of 0.9% NaCl solution?",
    options: ["4500 mg", "9000 mg", "450 mg", "900 mg"],
    correctAnswer: 0,
    explanation: "0.9% means 0.9 g per 100 mL. For 500 mL: 0.9 × 5 = 4.5 g = 4500 mg.",
    exam: "DHA", specialty: "pharmacy", topic: "CAL", difficulty: 1, phase: 1, day: 17,
  },
  {
    id: "ca2", text: "A patient weighs 70 kg. The dose is 5 mg/kg/day divided into 2 doses. What is each dose?",
    options: ["175 mg", "350 mg", "700 mg", "70 mg"],
    correctAnswer: 0,
    explanation: "Total daily dose = 5 mg/kg × 70 kg = 350 mg/day. Divided into 2 doses: 350/2 = 175 mg per dose.",
    exam: "MOH", specialty: "pharmacy", topic: "CAL", difficulty: 1, phase: 1, day: 17,
  },
  {
    id: "ca3", text: "If 1 mL of a solution contains 250 mg of amoxicillin, how many mL are needed for a 375 mg dose?",
    options: ["1.25 mL", "1.5 mL", "2 mL", "0.75 mL"],
    correctAnswer: 1,
    explanation: "Volume = Desired dose / Concentration = 375 mg / (250 mg/mL) = 1.5 mL.",
    exam: "SLE", specialty: "pharmacy", topic: "CAL", difficulty: 1, phase: 1, day: 17,
  },
  {
    id: "ca4", text: "What is the flow rate (drops/min) for 1000 mL IV fluid over 8 hours with a drop factor of 20 drops/mL?",
    options: ["42 drops/min", "21 drops/min", "63 drops/min", "32 drops/min"],
    correctAnswer: 0,
    explanation: "Flow rate = (Volume × Drop factor) / (Time in minutes) = (1000 × 20) / (8 × 60) = 20000/480 ≈ 42 drops/min.",
    exam: "HAAD", specialty: "pharmacy", topic: "CAL", difficulty: 2, phase: 2, day: 21,
  },
  {
    id: "ca5", text: "A cream contains 2% w/w active ingredient. How many grams of active ingredient are in 60 g of cream?",
    options: ["0.12 g", "1.2 g", "12 g", "0.6 g"],
    correctAnswer: 1,
    explanation: "2% w/w = 2 g per 100 g. In 60 g: (2/100) × 60 = 1.2 g of active ingredient.",
    exam: "DHA", specialty: "pharmacy", topic: "CAL", difficulty: 1, phase: 1, day: 17,
  },

  // SAFTY — Patient Safety (5)
  {
    id: "sa1", text: "Which is the most common type of medication error?",
    options: ["Wrong drug dispensed", "Wrong dose prescribed", "Omission error", "Wrong route of administration"],
    correctAnswer: 2,
    explanation: "Omission errors (failure to administer a prescribed dose) are the most common medication errors in healthcare settings, accounting for up to 30% of all medication errors.",
    exam: "DHA", specialty: "pharmacy", topic: "SAFTY", difficulty: 1, phase: 1, day: 25,
  },
  {
    id: "sa2", text: "Tall man lettering is used to differentiate:",
    options: ["Generic from brand names", "Look-alike, sound-alike (LASA) medications", "Controlled from non-controlled substances", "Oral from injectable formulations"],
    correctAnswer: 1,
    explanation: "Tall man lettering (e.g., DOBUTamine vs DOPamine, hydrOXYzine vs hydrALAZINE) is an FDA-recommended strategy to differentiate look-alike, sound-alike drug names and prevent errors.",
    exam: "MOH", specialty: "pharmacy", topic: "SAFTY", difficulty: 1, phase: 1, day: 25,
  },
  {
    id: "sa3", text: "A high-alert medication requires extra safeguards because it:",
    options: ["Is expensive", "Bears a heightened risk of significant patient harm if used in error", "Is a controlled substance", "Requires refrigeration"],
    correctAnswer: 1,
    explanation: "High-alert medications (defined by ISMP) carry heightened risk of significant harm when used in error. Examples include insulin, anticoagulants, opioids, and chemotherapy agents.",
    exam: "SLE", specialty: "pharmacy", topic: "SAFTY", difficulty: 1, phase: 1, day: 25,
  },
  {
    id: "sa4", text: "The 'five rights' of medication administration include all EXCEPT:",
    options: ["Right patient", "Right dose", "Right documentation", "Right cost"],
    correctAnswer: 3,
    explanation: "The five rights are: Right patient, Right drug, Right dose, Right route, and Right time. Right documentation is sometimes added as a sixth right, but cost is not included.",
    exam: "HAAD", specialty: "pharmacy", topic: "SAFTY", difficulty: 1, phase: 1, day: 25,
  },
  {
    id: "sa5", text: "Which organization publishes the 'Do Not Use' abbreviation list?",
    options: ["FDA", "WHO", "The Joint Commission (TJC)", "ASHP"],
    correctAnswer: 2,
    explanation: "The Joint Commission (TJC) publishes the official 'Do Not Use' list of dangerous abbreviations (e.g., U for units, QD for daily) to prevent medication errors in accredited organizations.",
    exam: "DHA", specialty: "pharmacy", topic: "SAFTY", difficulty: 2, phase: 2, day: 25,
  },

  // THER — Therapeutics (5)
  {
    id: "th1", text: "First-line treatment for H. pylori eradication is:",
    options: ["Amoxicillin alone for 14 days", "PPI + clarithromycin + amoxicillin for 14 days", "Metronidazole alone for 7 days", "H2 blocker + bismuth for 10 days"],
    correctAnswer: 1,
    explanation: "Standard triple therapy (PPI + clarithromycin + amoxicillin or metronidazole for 14 days) remains first-line for H. pylori. Bismuth quadruple therapy is an alternative.",
    exam: "DHA", specialty: "pharmacy", topic: "THER", difficulty: 1, phase: 1, day: 10,
  },
  {
    id: "th2", text: "In a patient with CKD stage 4, which phosphate binder should be AVOIDED?",
    options: ["Sevelamer", "Lanthanum carbonate", "Aluminum hydroxide (long-term)", "Calcium acetate"],
    correctAnswer: 2,
    explanation: "Aluminum-containing phosphate binders should be avoided long-term in CKD due to risk of aluminum toxicity (encephalopathy, osteomalacia, anemia). Short-term use only if alternatives fail.",
    exam: "MOH", specialty: "pharmacy", topic: "THER", difficulty: 3, phase: 3, day: 35,
  },
  {
    id: "th3", text: "The target INR range for a patient with a mechanical mitral valve on warfarin is:",
    options: ["1.5-2.0", "2.0-3.0", "2.5-3.5", "3.5-4.5"],
    correctAnswer: 2,
    explanation: "Mechanical mitral valves require a higher INR target of 2.5-3.5 due to higher thrombotic risk compared to mechanical aortic valves (target INR 2.0-3.0 for most).",
    exam: "SLE", specialty: "pharmacy", topic: "THER", difficulty: 2, phase: 2, day: 12,
  },
  {
    id: "th4", text: "Which medication requires REMS (Risk Evaluation and Mitigation Strategy) with iPLEDGE program?",
    options: ["Methotrexate", "Isotretinoin", "Clozapine", "Thalidomide"],
    correctAnswer: 1,
    explanation: "Isotretinoin requires the iPLEDGE REMS program due to severe teratogenicity. Patients must have negative pregnancy tests, use two forms of contraception, and register in the program.",
    exam: "HAAD", specialty: "pharmacy", topic: "THER", difficulty: 2, phase: 2, day: 26,
  },
  {
    id: "th5", text: "For acute migraine in a patient with cardiovascular disease, which drug class should be AVOIDED?",
    options: ["NSAIDs", "Triptans", "Antiemetics", "Acetaminophen"],
    correctAnswer: 1,
    explanation: "Triptans (5-HT1B/1D agonists) cause coronary vasoconstriction and are contraindicated in patients with cardiovascular disease, uncontrolled hypertension, or history of stroke/MI.",
    exam: "DHA", specialty: "pharmacy", topic: "THER", difficulty: 2, phase: 2, day: 8,
  },

  // PAIN — Pain Management (5)
  {
    id: "pa1", text: "Which opioid is preferred for moderate pain and has a ceiling effect for respiratory depression?",
    options: ["Morphine", "Fentanyl", "Buprenorphine", "Oxycodone"],
    correctAnswer: 2,
    explanation: "Buprenorphine is a partial mu-opioid agonist with a ceiling effect for respiratory depression, making it safer. It's used for moderate-severe pain and opioid use disorder.",
    exam: "DHA", specialty: "pharmacy", topic: "PAIN", difficulty: 2, phase: 2, day: 31,
  },
  {
    id: "pa2", text: "The antidote for opioid overdose is:",
    options: ["Flumazenil", "Naloxone", "N-acetylcysteine", "Atropine"],
    correctAnswer: 1,
    explanation: "Naloxone is a competitive mu-opioid antagonist that rapidly reverses opioid effects. It has a shorter half-life than most opioids, so repeat doses or infusion may be needed.",
    exam: "MOH", specialty: "pharmacy", topic: "PAIN", difficulty: 1, phase: 1, day: 31,
  },
  {
    id: "pa3", text: "Which NSAID is a selective COX-2 inhibitor?",
    options: ["Ibuprofen", "Naproxen", "Celecoxib", "Aspirin"],
    correctAnswer: 2,
    explanation: "Celecoxib is the only selective COX-2 inhibitor currently available. It has lower GI toxicity than non-selective NSAIDs but carries similar cardiovascular risks.",
    exam: "SLE", specialty: "pharmacy", topic: "PAIN", difficulty: 1, phase: 1, day: 8,
  },
  {
    id: "pa4", text: "Gabapentin is primarily indicated for which type of pain?",
    options: ["Acute inflammatory pain", "Neuropathic pain", "Visceral pain", "Bone fracture pain"],
    correctAnswer: 1,
    explanation: "Gabapentin (and pregabalin) binds to alpha-2-delta subunit of voltage-gated calcium channels, reducing neurotransmitter release. It's first-line for neuropathic pain (diabetic neuropathy, PHN).",
    exam: "HAAD", specialty: "pharmacy", topic: "PAIN", difficulty: 1, phase: 1, day: 31,
  },
  {
    id: "pa5", text: "Maximum daily dose of acetaminophen in a healthy adult is:",
    options: ["2000 mg", "3000 mg", "4000 mg", "5000 mg"],
    correctAnswer: 2,
    explanation: "Maximum daily dose of acetaminophen is 4000 mg (4 g) in healthy adults. For patients with liver disease or chronic alcohol use, the maximum is typically reduced to 2000 mg/day.",
    exam: "DHA", specialty: "pharmacy", topic: "PAIN", difficulty: 1, phase: 1, day: 8,
  },
];
