import { Question } from "./types";

export const seedQuestions: Question[] = [
  // Phase 1 - Foundation (difficulty 1)
  {
    id: "q1",
    text: "Which of the following is the most common cause of acute myocardial infarction?",
    options: ["A) Coronary artery spasm", "B) Atherosclerotic plaque rupture", "C) Coronary artery dissection", "D) Coronary embolism"],
    correctAnswer: 1,
    explanation: "Atherosclerotic plaque rupture with subsequent thrombus formation is the most common cause of acute MI, accounting for approximately 70% of cases. The rupture exposes the lipid core to circulating blood, triggering platelet aggregation and thrombus formation.",
    exam: "DHA",
    specialty: "medicine",
    topic: "cardiology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q2",
    text: "A 55-year-old male presents with crushing chest pain radiating to the left arm. ECG shows ST elevation in leads II, III, and aVF. Which coronary artery is most likely occluded?",
    options: ["A) Left anterior descending", "B) Left circumflex", "C) Right coronary artery", "D) Left main coronary artery"],
    correctAnswer: 2,
    explanation: "ST elevation in leads II, III, and aVF indicates an inferior MI, which is most commonly caused by occlusion of the right coronary artery (RCA). The RCA supplies the inferior wall of the left ventricle in approximately 85% of patients.",
    exam: "DHA",
    specialty: "medicine",
    topic: "cardiology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q3",
    text: "Which class of antihypertensive drugs is contraindicated in bilateral renal artery stenosis?",
    options: ["A) Calcium channel blockers", "B) ACE inhibitors", "C) Beta-blockers", "D) Thiazide diuretics"],
    correctAnswer: 1,
    explanation: "ACE inhibitors are contraindicated in bilateral renal artery stenosis because they reduce efferent arteriolar tone, which is essential for maintaining GFR when renal perfusion is compromised. This can lead to acute kidney injury.",
    exam: "MOH",
    specialty: "medicine",
    topic: "pharmacology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q4",
    text: "What is the first-line treatment for Helicobacter pylori infection?",
    options: ["A) Amoxicillin alone for 14 days", "B) Triple therapy: PPI + clarithromycin + amoxicillin", "C) Metronidazole monotherapy", "D) Bismuth subsalicylate alone"],
    correctAnswer: 1,
    explanation: "First-line treatment for H. pylori is triple therapy consisting of a proton pump inhibitor (PPI) combined with clarithromycin and amoxicillin for 14 days. This regimen achieves eradication rates of approximately 80-85%.",
    exam: "SLE",
    specialty: "medicine",
    topic: "gastroenterology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q5",
    text: "Which electrolyte abnormality is most commonly associated with prolonged QT interval?",
    options: ["A) Hyperkalemia", "B) Hypomagnesemia", "C) Hypernatremia", "D) Hypercalcemia"],
    correctAnswer: 1,
    explanation: "Hypomagnesemia is strongly associated with QT prolongation and can lead to torsades de pointes. Magnesium is essential for proper cardiac repolarization. Hypokalemia and hypocalcemia also prolong QT, but hypomagnesemia is a commonly tested association.",
    exam: "HAAD",
    specialty: "medicine",
    topic: "cardiology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q6",
    text: "A patient on warfarin therapy has an INR of 8.5 with no active bleeding. What is the most appropriate management?",
    options: ["A) Administer fresh frozen plasma", "B) Hold warfarin and give oral vitamin K", "C) Continue warfarin at current dose", "D) Administer prothrombin complex concentrate"],
    correctAnswer: 1,
    explanation: "For an INR >4.5 without significant bleeding, the recommended approach is to hold warfarin and administer oral vitamin K (2.5-5mg). FFP and PCC are reserved for active significant bleeding. The INR should be rechecked in 24-48 hours.",
    exam: "DHA",
    specialty: "medicine",
    topic: "hematology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q7",
    text: "Which of the following is the most sensitive marker for detecting acute kidney injury?",
    options: ["A) Blood urea nitrogen (BUN)", "B) Serum creatinine", "C) Serum cystatin C", "D) Urine specific gravity"],
    correctAnswer: 2,
    explanation: "Serum cystatin C is a more sensitive and earlier marker of AKI compared to creatinine. It is freely filtered by the glomerulus and not affected by muscle mass, diet, or sex. However, serum creatinine remains the most commonly used marker in clinical practice.",
    exam: "MOH",
    specialty: "medicine",
    topic: "nephrology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q8",
    text: "Which type of insulin has the longest duration of action?",
    options: ["A) Insulin lispro", "B) Regular insulin", "C) NPH insulin", "D) Insulin degludec"],
    correctAnswer: 3,
    explanation: "Insulin degludec (Tresiba) has the longest duration of action among available insulins, lasting up to 42 hours. It forms multi-hexamer chains after subcutaneous injection, creating a depot that slowly releases insulin monomers.",
    exam: "SLE",
    specialty: "medicine",
    topic: "endocrinology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q9",
    text: "A 30-year-old female presents with fatigue, weight gain, and cold intolerance. TSH is elevated and free T4 is low. What is the most likely diagnosis?",
    options: ["A) Graves' disease", "B) Hashimoto's thyroiditis", "C) Subacute thyroiditis", "D) Toxic multinodular goiter"],
    correctAnswer: 1,
    explanation: "The combination of elevated TSH with low free T4 indicates primary hypothyroidism. In a young female, Hashimoto's thyroiditis (chronic autoimmune thyroiditis) is the most common cause. It is characterized by anti-TPO and anti-thyroglobulin antibodies.",
    exam: "HAAD",
    specialty: "medicine",
    topic: "endocrinology",
    difficulty: 1,
    phase: 1,
  },
  {
    id: "q10",
    text: "Which pneumonia pathogen is most commonly associated with 'currant jelly' sputum?",
    options: ["A) Streptococcus pneumoniae", "B) Klebsiella pneumoniae", "C) Mycoplasma pneumoniae", "D) Legionella pneumophila"],
    correctAnswer: 1,
    explanation: "Klebsiella pneumoniae classically produces thick, bloody, mucoid sputum described as 'currant jelly.' It typically affects alcoholics and debilitated patients, causing cavitary lesions predominantly in the upper lobes.",
    exam: "DHA",
    specialty: "medicine",
    topic: "pulmonology",
    difficulty: 1,
    phase: 1,
  },
  // Phase 2 - Intermediate (difficulty 2)
  {
    id: "q11",
    text: "A patient with heart failure is started on carvedilol. Which of the following best describes the mechanism of action?",
    options: ["A) Selective beta-1 blockade", "B) Non-selective beta blockade with alpha-1 blockade", "C) Selective alpha-1 blockade", "D) Non-selective beta blockade only"],
    correctAnswer: 1,
    explanation: "Carvedilol is a non-selective beta-blocker (blocks both β1 and β2 receptors) with additional alpha-1 blocking activity. The alpha-1 blockade provides vasodilation, which is beneficial in heart failure by reducing afterload.",
    exam: "DHA",
    specialty: "medicine",
    topic: "pharmacology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q12",
    text: "In diabetic ketoacidosis, which of the following is the most important initial step in management?",
    options: ["A) Insulin bolus", "B) Sodium bicarbonate infusion", "C) Isotonic saline resuscitation", "D) Potassium replacement"],
    correctAnswer: 2,
    explanation: "The most important initial step in DKA management is aggressive IV fluid resuscitation with isotonic (0.9%) normal saline. Patients are typically 5-7 liters depleted. Insulin should be started after ensuring adequate hydration and confirming potassium >3.3 mEq/L.",
    exam: "MOH",
    specialty: "medicine",
    topic: "endocrinology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q13",
    text: "A 65-year-old male presents with sudden onset severe headache described as 'the worst headache of my life.' CT head is negative. What is the next best step?",
    options: ["A) MRI brain", "B) Lumbar puncture", "C) CT angiography", "D) Discharge with analgesics"],
    correctAnswer: 1,
    explanation: "When subarachnoid hemorrhage (SAH) is clinically suspected but CT is negative (sensitivity ~95% at 12h, decreasing over time), lumbar puncture is the next essential step to look for xanthochromia or RBCs. A negative CT does not rule out SAH.",
    exam: "SLE",
    specialty: "medicine",
    topic: "neurology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q14",
    text: "Which of the following is the most common cause of secondary hypertension in young adults?",
    options: ["A) Pheochromocytoma", "B) Renal artery stenosis (fibromuscular dysplasia)", "C) Primary aldosteronism", "D) Cushing syndrome"],
    correctAnswer: 1,
    explanation: "Fibromuscular dysplasia (FMD) causing renal artery stenosis is the most common cause of secondary hypertension in young adults, particularly young women. It typically presents with resistant hypertension and may have an abdominal bruit.",
    exam: "HAAD",
    specialty: "medicine",
    topic: "nephrology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q15",
    text: "A patient with chronic liver disease presents with confusion and asterixis. Serum ammonia is elevated. Which of the following is the first-line treatment?",
    options: ["A) Neomycin", "B) Lactulose", "C) Rifaximin", "D) Flumazenil"],
    correctAnswer: 1,
    explanation: "Lactulose is the first-line treatment for hepatic encephalopathy. It works by acidifying colonic contents (converting ammonia to ammonium which cannot be absorbed) and acting as an osmotic laxative to increase fecal nitrogen excretion.",
    exam: "DHA",
    specialty: "medicine",
    topic: "gastroenterology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q16",
    text: "Which autoantibody is most specific for systemic lupus erythematosus?",
    options: ["A) Anti-nuclear antibody (ANA)", "B) Anti-double stranded DNA (anti-dsDNA)", "C) Anti-Smith (anti-Sm)", "D) Anti-histone antibody"],
    correctAnswer: 2,
    explanation: "Anti-Smith (anti-Sm) antibody is the most specific autoantibody for SLE, though it has low sensitivity (~30%). Anti-dsDNA is both fairly specific and correlates with disease activity, especially lupus nephritis. ANA is sensitive but not specific.",
    exam: "MOH",
    specialty: "medicine",
    topic: "rheumatology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q17",
    text: "A 45-year-old woman presents with episodic headaches, sweating, and palpitations. Her blood pressure is 210/120 mmHg. Which test should be ordered first?",
    options: ["A) 24-hour urine cortisol", "B) Plasma metanephrines", "C) Serum aldosterone/renin ratio", "D) Renal artery duplex ultrasound"],
    correctAnswer: 1,
    explanation: "The classic triad of episodic headaches, sweating, and palpitations with severe hypertension suggests pheochromocytoma. Plasma free metanephrines is the recommended initial screening test with sensitivity >96% and specificity >85%.",
    exam: "SLE",
    specialty: "medicine",
    topic: "endocrinology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q18",
    text: "Which of the following drugs is most likely to cause drug-induced lupus?",
    options: ["A) Hydralazine", "B) Metformin", "C) Amlodipine", "D) Atorvastatin"],
    correctAnswer: 0,
    explanation: "Hydralazine is one of the most common causes of drug-induced lupus, along with procainamide, isoniazid, and minocycline. Drug-induced lupus typically presents with anti-histone antibodies and resolves upon drug discontinuation.",
    exam: "HAAD",
    specialty: "medicine",
    topic: "rheumatology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q19",
    text: "A patient with atrial fibrillation has a CHA₂DS₂-VASc score of 3. What is the recommended anticoagulation?",
    options: ["A) Aspirin alone", "B) No anticoagulation needed", "C) Direct oral anticoagulant (DOAC)", "D) Dual antiplatelet therapy"],
    correctAnswer: 2,
    explanation: "A CHA₂DS₂-VASc score ≥2 in males or ≥3 in females warrants oral anticoagulation. DOACs (dabigatran, rivaroxaban, apixaban, edoxaban) are preferred over warfarin for non-valvular AF due to better safety profile and no need for INR monitoring.",
    exam: "DHA",
    specialty: "medicine",
    topic: "cardiology",
    difficulty: 2,
    phase: 2,
  },
  {
    id: "q20",
    text: "Which of the following is the most common cause of community-acquired pneumonia in adults?",
    options: ["A) Haemophilus influenzae", "B) Streptococcus pneumoniae", "C) Mycoplasma pneumoniae", "D) Staphylococcus aureus"],
    correctAnswer: 1,
    explanation: "Streptococcus pneumoniae remains the most common cause of community-acquired pneumonia in adults worldwide. It typically presents with acute onset fever, productive cough with rusty sputum, and lobar consolidation on chest X-ray.",
    exam: "MOH",
    specialty: "medicine",
    topic: "pulmonology",
    difficulty: 2,
    phase: 2,
  },
  // Phase 3 - Exam Ready (difficulty 3)
  {
    id: "q21",
    text: "A 60-year-old male with COPD presents with acute worsening dyspnea. ABG shows pH 7.28, pCO2 65, HCO3 30, pO2 55. Which acid-base disorder is present?",
    options: ["A) Acute respiratory acidosis", "B) Chronic respiratory acidosis with acute decompensation", "C) Mixed respiratory and metabolic acidosis", "D) Acute metabolic acidosis with respiratory compensation"],
    correctAnswer: 1,
    explanation: "The elevated HCO3 (30) indicates chronic renal compensation for respiratory acidosis. However, the low pH (7.28) indicates inadequate compensation, suggesting acute-on-chronic (decompensated) respiratory acidosis. In pure chronic respiratory acidosis, pH would be closer to normal.",
    exam: "DHA",
    specialty: "medicine",
    topic: "pulmonology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q22",
    text: "A patient with suspected pulmonary embolism has a Wells score of 6. D-dimer is elevated. CT pulmonary angiography is contraindicated. What is the best alternative diagnostic test?",
    options: ["A) Chest X-ray", "B) V/Q scan", "C) Lower extremity Doppler ultrasound", "D) Echocardiography"],
    correctAnswer: 1,
    explanation: "When CTPA is contraindicated (e.g., contrast allergy, renal failure), V/Q (ventilation-perfusion) scan is the best alternative imaging study. A high-probability V/Q scan in a patient with high clinical suspicion has >95% positive predictive value for PE.",
    exam: "MOH",
    specialty: "medicine",
    topic: "pulmonology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q23",
    text: "A 35-year-old presents with recurrent deep vein thrombosis. Workup reveals activated protein C resistance. What is the most likely underlying genetic mutation?",
    options: ["A) Prothrombin G20210A mutation", "B) Factor V Leiden mutation", "C) Antithrombin III deficiency", "D) Protein S deficiency"],
    correctAnswer: 1,
    explanation: "Factor V Leiden mutation is the most common inherited thrombophilia and the most common cause of activated protein C (APC) resistance. The mutation makes Factor V resistant to inactivation by activated protein C, leading to a hypercoagulable state.",
    exam: "SLE",
    specialty: "medicine",
    topic: "hematology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q24",
    text: "A patient with chronic kidney disease stage 4 develops secondary hyperparathyroidism. Which of the following is the initial pathophysiological trigger?",
    options: ["A) Decreased calcitriol production", "B) Hyperphosphatemia", "C) Decreased FGF-23 levels", "D) Increased calcium absorption"],
    correctAnswer: 0,
    explanation: "The initial trigger in CKD-related secondary hyperparathyroidism is decreased renal 1-alpha hydroxylase activity, leading to reduced calcitriol (1,25-dihydroxyvitamin D) production. This causes decreased intestinal calcium absorption, hypocalcemia, and compensatory PTH elevation.",
    exam: "HAAD",
    specialty: "medicine",
    topic: "nephrology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q25",
    text: "A patient with infective endocarditis develops sudden onset left-sided weakness. CT brain shows a hyperdense lesion in the right MCA territory. What is the most likely mechanism?",
    options: ["A) Mycotic aneurysm rupture", "B) Septic embolism with hemorrhagic transformation", "C) Thrombotic stroke from carotid stenosis", "D) Hypertensive intracerebral hemorrhage"],
    correctAnswer: 1,
    explanation: "In infective endocarditis, septic emboli from cardiac vegetations can occlude cerebral arteries causing ischemic stroke, which may undergo hemorrhagic transformation. This is the most common neurological complication of IE, occurring in 20-40% of cases.",
    exam: "DHA",
    specialty: "medicine",
    topic: "cardiology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q26",
    text: "A 50-year-old alcoholic male presents with ascites. Diagnostic paracentesis shows SAAG 1.8 g/dL and total protein 1.5 g/dL. Which is the most likely cause?",
    options: ["A) Peritoneal tuberculosis", "B) Portal hypertension from cirrhosis", "C) Nephrotic syndrome", "D) Peritoneal carcinomatosis"],
    correctAnswer: 1,
    explanation: "A SAAG ≥1.1 g/dL indicates portal hypertension. Combined with low ascitic protein (<2.5 g/dL) in an alcoholic patient, cirrhosis with portal hypertension is the most likely diagnosis. TB and carcinomatosis cause exudative ascites with SAAG <1.1.",
    exam: "MOH",
    specialty: "medicine",
    topic: "gastroenterology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q27",
    text: "Which of the following is the most appropriate initial treatment for acute STEMI if primary PCI cannot be performed within 120 minutes of first medical contact?",
    options: ["A) Heparin infusion alone", "B) Fibrinolytic therapy", "C) Dual antiplatelet therapy only", "D) Emergency CABG"],
    correctAnswer: 1,
    explanation: "When primary PCI cannot be performed within 120 minutes of first medical contact, fibrinolytic therapy should be administered within 30 minutes (door-to-needle time). Tenecteplase or alteplase are commonly used. Transfer for rescue PCI should follow if fibrinolysis fails.",
    exam: "SLE",
    specialty: "medicine",
    topic: "cardiology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q28",
    text: "A patient with type 2 diabetes and CKD stage 3b (eGFR 35) needs additional glycemic control. Which medication class has shown the greatest renal protective benefit?",
    options: ["A) DPP-4 inhibitors", "B) SGLT2 inhibitors", "C) Sulfonylureas", "D) Thiazolidinediones"],
    correctAnswer: 1,
    explanation: "SGLT2 inhibitors (empagliflozin, dapagliflozin, canagliflozin) have demonstrated significant renal protective benefits in major trials (CREDENCE, DAPA-CKD). They reduce progression of diabetic kidney disease, albuminuria, and risk of renal replacement therapy independent of glycemic effects.",
    exam: "HAAD",
    specialty: "medicine",
    topic: "nephrology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q29",
    text: "A 70-year-old presents with normocytic anemia, elevated ESR, and serum protein electrophoresis showing an M-spike. Bone marrow biopsy shows 35% plasma cells. What is the diagnosis?",
    options: ["A) Monoclonal gammopathy of undetermined significance (MGUS)", "B) Multiple myeloma", "C) Waldenström macroglobulinemia", "D) Amyloidosis"],
    correctAnswer: 1,
    explanation: "Multiple myeloma is diagnosed when bone marrow plasma cells are ≥10% (this patient has 35%) plus evidence of end-organ damage (CRAB: Calcium elevation, Renal insufficiency, Anemia, Bone lesions) or biomarkers of malignancy. MGUS has <10% plasma cells and no organ damage.",
    exam: "DHA",
    specialty: "medicine",
    topic: "hematology",
    difficulty: 3,
    phase: 3,
  },
  {
    id: "q30",
    text: "A patient in the ICU develops acute respiratory distress syndrome (ARDS). Which ventilation strategy has been shown to reduce mortality?",
    options: ["A) High tidal volume (12 mL/kg) ventilation", "B) Low tidal volume (6 mL/kg ideal body weight) ventilation", "C) Inverse ratio ventilation", "D) High-frequency oscillatory ventilation"],
    correctAnswer: 1,
    explanation: "The ARDSNet trial demonstrated that low tidal volume ventilation (6 mL/kg of ideal body weight) with plateau pressure <30 cmH2O significantly reduces mortality in ARDS compared to conventional ventilation. This lung-protective strategy minimizes ventilator-induced lung injury.",
    exam: "MOH",
    specialty: "medicine",
    topic: "critical care",
    difficulty: 3,
    phase: 3,
  },
];
